import type { CardDef, CardInst, CharacterId } from "./types";
import { asset } from "@/lib/asset";
import { uid } from "./rng";
import { SHOP_CARDS } from "./smith";

export const DECK_LIMIT = 20;

export const CARDS: Record<string, CardDef> = {
  strike: {
    id: "strike",
    name: "打撃",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "starter",
    owner: "investigator",
    text: "6ダメージ。",
    upgradedText: "9ダメージ。",
    flavor: "肉体は、まだ拳を信じている。",
    art: asset("art/pixel/cards/strike.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 6 }],
    upgradedEffects: [{ t: "damage", n: 9 }],
  },
  ward: {
    id: "ward",
    name: "結界",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "starter",
    owner: "investigator",
    text: "ブロック5を得る。",
    upgradedText: "ブロック8を得る。",
    flavor: "塩の円。長くは持たない。",
    art: asset("art/pixel/cards/ward.jpg"),
    target: "none",
    effects: [{ t: "block", n: 5 }],
    upgradedEffects: [{ t: "block", n: 8 }],
  },
  study: {
    id: "study",
    name: "精読",
    type: "skill",
    aiTag: "effect",
    cost: 1,
    rarity: "starter",
    owner: "investigator",
    text: "2枚引く。正気を2失う。",
    upgradedText: "3枚引く。正気を2失う。",
    flavor: "一頁ごとに、少しずつ削れる。",
    art: asset("art/pixel/cards/study.jpg"),
    target: "none",
    effects: [{ t: "draw", n: 2 }, { t: "sanity", n: -2 }],
    upgradedEffects: [{ t: "draw", n: 3 }, { t: "sanity", n: -2 }],
  },
  lash: {
    id: "lash",
    name: "鞭撃",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "starter",
    owner: "cultist",
    text: "7ダメージ。",
    upgradedText: "10ダメージ。",
    flavor: "打てば、何かが応える。",
    art: asset("art/pixel/cards/lash.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 7 }],
    upgradedEffects: [{ t: "damage", n: 10 }],
  },
  sigil: {
    id: "sigil",
    name: "印",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "starter",
    owner: "cultist",
    text: "ブロック5を得る。",
    upgradedText: "ブロック8を得る。",
    flavor: "掌の印が、冷たく燃える。",
    art: asset("art/pixel/cards/sigil.jpg"),
    target: "none",
    effects: [{ t: "block", n: 5 }],
    upgradedEffects: [{ t: "block", n: 8 }],
  },
  whisper: {
    id: "whisper",
    name: "囁き",
    type: "skill",
    aiTag: "effect",
    cost: 0,
    rarity: "starter",
    owner: "cultist",
    text: "1枚引く。正気を2失う。",
    upgradedText: "2枚引く。正気を2失う。",
    flavor: "すでに、話していた。",
    art: asset("art/pixel/cards/whisper.jpg"),
    target: "none",
    effects: [{ t: "draw", n: 1 }, { t: "sanity", n: -2 }],
    upgradedEffects: [{ t: "draw", n: 2 }, { t: "sanity", n: -2 }],
  },
  precise: {
    id: "precise",
    name: "計測打撃",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "common",
    owner: "investigator",
    text: "8ダメージ。敵の意図が攻撃なら、さらに5。",
    upgradedText: "11ダメージ。敵の意図が攻撃なら、さらに6。",
    flavor: "死にかけても、記録は続ける。",
    art: asset("art/card-strike.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 8 }, { t: "ifIntentAttack", then: [{ t: "damage", n: 5 }] }],
    upgradedEffects: [{ t: "damage", n: 11 }, { t: "ifIntentAttack", then: [{ t: "damage", n: 6 }] }],
  },
  dressing: {
    id: "dressing",
    name: "応急処置",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "common",
    owner: "investigator",
    text: "ブロック7を得る。3回復。",
    upgradedText: "ブロック10を得る。4回復。",
    flavor: "布と、意地。",
    art: asset("art/card-ward.jpg"),
    target: "none",
    effects: [{ t: "block", n: 7 }, { t: "heal", n: 3 }],
    upgradedEffects: [{ t: "block", n: 10 }, { t: "heal", n: 4 }],
  },
  bloodpact: {
    id: "bloodpact",
    name: "血契",
    type: "skill",
    aiTag: "effect",
    cost: 0,
    rarity: "common",
    owner: "shared",
    text: "体力を4失う。エネルギーを2得る。",
    upgradedText: "体力を3失う。エネルギーを2得る。",
    flavor: "インクは、インク以上を受け入れる。",
    art: asset("art/card-rite.jpg"),
    target: "none",
    effects: [{ t: "hpCost", n: 4 }, { t: "energy", n: 2 }],
    upgradedEffects: [{ t: "hpCost", n: 3 }, { t: "energy", n: 2 }],
  },
  insight: {
    id: "insight",
    name: "啓示",
    type: "skill",
    aiTag: "effect",
    cost: 1,
    rarity: "common",
    owner: "shared",
    text: "2枚引く。エネルギーを1得る。正気を3失う。",
    upgradedText: "3枚引く。エネルギーを1得る。正気を3失う。",
    flavor: "模様は、最初からそこにあった。",
    art: asset("art/card-study.jpg"),
    target: "none",
    effects: [{ t: "draw", n: 2 }, { t: "energy", n: 1 }, { t: "sanity", n: -3 }],
    upgradedEffects: [{ t: "draw", n: 3 }, { t: "energy", n: 1 }, { t: "sanity", n: -3 }],
  },
  offering: {
    id: "offering",
    name: "供物",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "common",
    owner: "cultist",
    text: "正気を5失う。14ダメージ。",
    upgradedText: "正気を4失う。18ダメージ。",
    flavor: "それは、君の味を好む。",
    art: asset("art/card-lash.jpg"),
    target: "enemy",
    effects: [{ t: "sanity", n: -5 }, { t: "damage", n: 14 }],
    upgradedEffects: [{ t: "sanity", n: -4 }, { t: "damage", n: 18 }],
  },
  chant: {
    id: "chant",
    name: "詠唱",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "common",
    owner: "cultist",
    text: "ブロック6を得る。筋力を2得る。",
    upgradedText: "ブロック8を得る。筋力を3得る。",
    flavor: "言葉が、自分を知っている。",
    art: asset("art/card-rite.jpg"),
    target: "none",
    effects: [{ t: "block", n: 6 }, { t: "strength", n: 2 }],
    upgradedEffects: [{ t: "block", n: 8 }, { t: "strength", n: 3 }],
  },
  sweep: {
    id: "sweep",
    name: "闇の薙ぎ",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "common",
    owner: "cultist",
    text: "敵全体に5ダメージ。",
    upgradedText: "敵全体に8ダメージ。",
    flavor: "回廊は、見た目より長い。",
    art: asset("art/card-lash.jpg"),
    target: "all",
    effects: [{ t: "damageAll", n: 5 }],
    upgradedEffects: [{ t: "damageAll", n: 8 }],
  },
  ironwill: {
    id: "ironwill",
    name: "鉄の意志",
    type: "skill",
    aiTag: "defense",
    cost: 2,
    rarity: "uncommon",
    owner: "investigator",
    text: "ブロック12を得る。筋力を2得る。",
    upgradedText: "ブロック16を得る。筋力を3得る。",
    flavor: "廊下の形を、拒む。",
    art: asset("art/card-ward.jpg"),
    target: "none",
    effects: [{ t: "block", n: 12 }, { t: "strength", n: 2 }],
    upgradedEffects: [{ t: "block", n: 16 }, { t: "strength", n: 3 }],
  },
  resolve: {
    id: "resolve",
    name: "覚悟",
    type: "power",
    aiTag: "effect",
    cost: 1,
    rarity: "uncommon",
    owner: "investigator",
    text: "攻撃を出すたび、ブロック3を得る。",
    upgradedText: "攻撃を出すたび、ブロック4を得る。",
    flavor: "習慣は、希望より長く生きる。",
    art: asset("art/card-study.jpg"),
    target: "none",
    effects: [{ t: "gainPower", id: "resolve" }],
    upgradedEffects: [{ t: "gainPower", id: "resolve" }],
  },
  echo: {
    id: "echo",
    name: "残響",
    type: "power",
    aiTag: "effect",
    cost: 1,
    rarity: "uncommon",
    owner: "cultist",
    text: "自分のターン開始時、ランダムな敵に4ダメージ。",
    upgradedText: "自分のターン開始時、ランダムな敵に6ダメージ。",
    flavor: "声を、後ろに残した。",
    art: asset("art/card-rite.jpg"),
    target: "none",
    effects: [{ t: "gainPower", id: "echo" }],
    upgradedEffects: [{ t: "gainPower", id: "echo" }],
  },
  rite: {
    id: "rite",
    name: "眼の儀式",
    type: "skill",
    aiTag: "effect",
    cost: 0,
    rarity: "uncommon",
    owner: "cultist",
    text: "2枚引く。脆弱1を与える。正気を4失う。",
    upgradedText: "2枚引く。脆弱2を与える。正気を3失う。",
    flavor: "見よ。そして、見られよ。",
    art: asset("art/card-rite.jpg"),
    target: "enemy",
    effects: [{ t: "draw", n: 2 }, { t: "vulnerable", n: 1 }, { t: "sanity", n: -4 }],
    upgradedEffects: [{ t: "draw", n: 2 }, { t: "vulnerable", n: 2 }, { t: "sanity", n: -3 }],
  },
  oath: {
    id: "oath",
    name: "血の誓い",
    type: "power",
    aiTag: "effect",
    cost: 1,
    rarity: "uncommon",
    owner: "shared",
    text: "正気を失うたび、筋力を2得る。",
    upgradedText: "正気を失うたび、筋力を3得る。",
    flavor: "すでに署名した契約。",
    art: asset("art/card-tome.jpg"),
    target: "none",
    effects: [{ t: "gainPower", id: "bloodOath" }],
    upgradedEffects: [{ t: "gainPower", id: "bloodOath" }],
  },
  bash: {
    id: "bash",
    name: "破砕",
    type: "attack",
    aiTag: "attack",
    cost: 2,
    rarity: "uncommon",
    owner: "investigator",
    text: "10ダメージ。脆弱2を与える。",
    upgradedText: "13ダメージ。脆弱3を与える。",
    flavor: "扉の中には、人がいる。",
    art: asset("art/card-strike.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 10 }, { t: "vulnerable", n: 2 }],
    upgradedEffects: [{ t: "damage", n: 13 }, { t: "vulnerable", n: 3 }],
  },
  tome: {
    id: "tome",
    name: "禁断の書",
    type: "skill",
    aiTag: "effect",
    cost: 1,
    rarity: "rare",
    owner: "investigator",
    text: "3枚引く。筋力を2得る。正気を6失う。",
    upgradedText: "4枚引く。筋力を3得る。正気を5失う。",
    flavor: "最終章は、君の筆跡で書かれている。",
    art: asset("art/card-tome.jpg"),
    target: "none",
    effects: [{ t: "draw", n: 3 }, { t: "strength", n: 2 }, { t: "sanity", n: -6 }],
    upgradedEffects: [{ t: "draw", n: 4 }, { t: "strength", n: 3 }, { t: "sanity", n: -5 }],
  },
  eldersign: {
    id: "eldersign",
    name: "古の印",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "rare",
    owner: "shared",
    text: "ブロック15を得る。正気が20以下なら、敵全体に15ダメージ。",
    upgradedText: "ブロック20を得る。正気が25以下なら、敵全体に18ダメージ。",
    flavor: "古い戦争を覚えている護符。",
    art: asset("art/card-ward.jpg"),
    target: "none",
    effects: [
      { t: "block", n: 15 },
      { t: "ifSanityBelow", threshold: 21, then: [{ t: "damageAll", n: 15 }] },
    ],
    upgradedEffects: [
      { t: "block", n: 20 },
      { t: "ifSanityBelow", threshold: 26, then: [{ t: "damageAll", n: 18 }] },
    ],
  },
  thecall: {
    id: "thecall",
    name: "呼び声",
    type: "attack",
    aiTag: "attack",
    cost: 2,
    rarity: "rare",
    owner: "cultist",
    text: "敵全体に10ダメージ。弱体2。正気を6失う。破棄。",
    upgradedText: "敵全体に14ダメージ。弱体3。正気を5失う。破棄。",
    flavor: "母音を、待っていた。",
    art: asset("art/card-lash.jpg"),
    target: "all",
    exhaust: true,
    effects: [
      { t: "damageAll", n: 10 },
      { t: "weak", n: 2 },
      { t: "sanity", n: -6 },
    ],
    upgradedEffects: [
      { t: "damageAll", n: 14 },
      { t: "weak", n: 3 },
      { t: "sanity", n: -5 },
    ],
  },
  laststand: {
    id: "laststand",
    name: "最期の抵抗",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "rare",
    owner: "investigator",
    text: "9ダメージ。体力が半分以下なら、さらに9。",
    upgradedText: "12ダメージ。体力が半分以下なら、さらに12。",
    flavor: "記録の中では、すでに死んでいる。",
    art: asset("art/card-strike.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 9 }],
    upgradedEffects: [{ t: "damage", n: 12 }],
  },
  dread: {
    id: "dread",
    name: "恐怖",
    type: "status",
    cost: 0,
    rarity: "status",
    owner: "status",
    text: "プレイ不可。",
    upgradedText: "プレイ不可。",
    flavor: "手札に、歯のように坐る。",
    art: asset("art/card-study.jpg"),
    target: "none",
    unplayable: true,
    ethereal: true,
    effects: [],
    upgradedEffects: [],
  },
  frostbite: {
    id: "frostbite",
    name: "凍傷",
    type: "status",
    cost: 0,
    rarity: "status",
    owner: "status",
    text: "引いたとき 1 ダメージ。廃棄される。",
    upgradedText: "引いたとき 1 ダメージ。廃棄される。",
    flavor: "指先から、世界が止まる。",
    art: asset("art/card-ward.jpg"),
    target: "none",
    unplayable: true,
    ethereal: true,
    onDraw: [{ t: "hpCost", n: 1 }],
    effects: [],
    upgradedEffects: [],
  },
  "all-distortion": {
    id: "all-distortion",
    name: "空間の歪み",
    type: "skill",
    aiTag: "defense",
    cost: 1,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "ブロック8。1枚引く。使うたび最大体力を1失う。",
    upgradedText: "ブロック11。1枚引く。使うたび最大体力を1失う。",
    flavor: "落下は、解釈に過ぎない。",
    art: asset("art/card-tome.jpg"),
    target: "none",
    effects: [{ t: "block", n: 8 }, { t: "draw", n: 1 }, { t: "loseMaxHp", n: 1 }],
    upgradedEffects: [{ t: "block", n: 11 }, { t: "draw", n: 1 }, { t: "loseMaxHp", n: 1 }],
  },
  "all-zero": {
    id: "all-zero",
    name: "絶対零度の騙し絵",
    type: "attack",
    aiTag: "attack",
    cost: 2,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "14ダメージ。脱力2。捨て札に凍傷を1枚。",
    upgradedText: "18ダメージ。脱力2。捨て札に凍傷を1枚。",
    flavor: "熱量を、ゼロと再定義する。",
    art: asset("art/card-rite.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 14 }, { t: "weak", n: 2 }, { t: "addCurse", id: "frostbite" }],
    upgradedEffects: [{ t: "damage", n: 18 }, { t: "weak", n: 2 }, { t: "addCurse", id: "frostbite" }],
  },
  "all-geo": {
    id: "all-geo",
    name: "地磁気の強制共鳴",
    type: "attack",
    aiTag: "attack",
    cost: 3,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    exhaust: true,
    text: "敵全体に10。1体につきブロック6。自分は3（貫通）。廃棄。",
    upgradedText: "敵全体に14。1体につきブロック6。自分は3（貫通）。廃棄。",
    flavor: "血が、大地に縫われる。",
    art: asset("art/card-rite.jpg"),
    target: "all",
    effects: [{ t: "hpCost", n: 3 }, { t: "damageAll", n: 10 }, { t: "blockPerEnemy", n: 6 }],
    upgradedEffects: [{ t: "hpCost", n: 3 }, { t: "damageAll", n: 14 }, { t: "blockPerEnemy", n: 6 }],
  },
  "all-vacuum": {
    id: "all-vacuum",
    name: "擬似真空",
    type: "skill",
    aiTag: "effect",
    cost: 1,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "弱体1、毒5。このターン、攻撃するたび自分は1。",
    upgradedText: "弱体1、毒7。このターン、攻撃するたび自分は1。",
    flavor: "肺の中を、無にする。",
    art: asset("art/card-study.jpg"),
    target: "enemy",
    effects: [{ t: "weak", n: 1 }, { t: "poison", n: 5 }, { t: "attackSelfHurt", n: 1 }],
    upgradedEffects: [{ t: "weak", n: 1 }, { t: "poison", n: 7 }, { t: "attackSelfHurt", n: 1 }],
  },
  "all-phase": {
    id: "all-phase",
    name: "位相遅延",
    type: "skill",
    aiTag: "defense",
    cost: 2,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "ブロック12。次のターン開始時、このターン失ったブロック分ダメージ。",
    upgradedText: "ブロック16。次のターン開始時、このターン失ったブロック分ダメージ。",
    flavor: "痛みを、遅らせて返す。",
    art: asset("art/card-ward.jpg"),
    target: "none",
    effects: [{ t: "block", n: 12 }, { t: "phaseDelay" }],
    upgradedEffects: [{ t: "block", n: 16 }, { t: "phaseDelay" }],
  },
  "all-blind": {
    id: "all-blind",
    name: "知覚盲点",
    type: "skill",
    aiTag: "effect",
    cost: 1,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    exhaust: true,
    text: "無形1ターン。次の攻撃が2倍。廃棄。",
    upgradedText: "無形1ターン。次の攻撃が2倍。廃棄。",
    flavor: "光子を、届かせない。",
    art: asset("art/card-tome.jpg"),
    target: "none",
    effects: [{ t: "intangible", n: 1 }, { t: "nextAttackMul", n: 2 }],
    upgradedEffects: [{ t: "intangible", n: 1 }, { t: "nextAttackMul", n: 2 }],
  },
  "all-overclock": {
    id: "all-overclock",
    name: "シナプス・オーバークロック",
    type: "skill",
    aiTag: "effect",
    cost: 0,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "自分は4（貫通）。エネルギー+2。2枚引く。",
    upgradedText: "自分は4（貫通）。エネルギー+2。3枚引く。",
    flavor: "リミッターを、壊す。",
    art: asset("art/card-lash.jpg"),
    target: "none",
    effects: [{ t: "hpCost", n: 4 }, { t: "energy", n: 2 }, { t: "draw", n: 2 }],
    upgradedEffects: [{ t: "hpCost", n: 4 }, { t: "energy", n: 2 }, { t: "draw", n: 3 }],
  },
  "all-glass": {
    id: "all-glass",
    name: "骨格のガラス化",
    type: "attack",
    aiTag: "attack",
    cost: 1,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    text: "7ダメージ。脆弱2。",
    upgradedText: "7ダメージ。脆弱2。",
    flavor: "骨に、固有振動を与える。",
    art: asset("art/card-strike.jpg"),
    target: "enemy",
    effects: [{ t: "damage", n: 7 }, { t: "vulnerable", n: 2 }],
    upgradedEffects: [{ t: "damage", n: 7 }, { t: "vulnerable", n: 2 }],
  },
  "all-necrosis": {
    id: "all-necrosis",
    name: "壊死の伝播",
    type: "skill",
    aiTag: "effect",
    cost: 2,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    exhaust: true,
    text: "弱体2、毒9。廃棄。",
    upgradedText: "弱体2、毒12。廃棄。",
    flavor: "分裂を、止める。",
    art: asset("art/card-study.jpg"),
    target: "enemy",
    effects: [{ t: "weak", n: 2 }, { t: "poison", n: 9 }],
    upgradedEffects: [{ t: "weak", n: 2 }, { t: "poison", n: 12 }],
  },
  "all-diffuse": {
    id: "all-diffuse",
    name: "存在確率の拡散",
    type: "power",
    aiTag: "effect",
    cost: 3,
    rarity: "rare",
    owner: "shared",
    grimoire: true,
    exhaust: true,
    text: "無形2ターン。最大体力-3。廃棄。",
    upgradedText: "無形2ターン。最大体力-3。廃棄。",
    flavor: "そこにいる。そこにはいない。",
    art: asset("art/card-tome.jpg"),
    target: "none",
    effects: [{ t: "intangible", n: 2 }, { t: "loseMaxHp", n: 3 }],
    upgradedEffects: [{ t: "intangible", n: 2 }, { t: "loseMaxHp", n: 3 }],
  },
};

Object.assign(CARDS, SHOP_CARDS);

export function getCard(id: string): CardDef {
  const c = CARDS[id];
  if (!c) throw new Error(`Unknown card ${id}`);
  return c;
}

export function aiCardPool(tag: "attack" | "defense" | "effect"): CardDef[] {
  return Object.values(CARDS).filter(
    (c) => c.type !== "status" && c.type !== "power" && c.aiTag === tag,
  );
}

export function makeCard(defId: string, upgraded = false): CardInst {
  const d = getCard(defId);
  return { uid: uid("c"), defId, upgraded, charges: d.charges, forge: undefined };
}

export function cardText(card: CardInst): string {
  const d = getCard(card.defId);
  return card.upgraded ? d.upgradedText : d.text;
}

export function cardCost(card: CardInst): number {
  const d = getCard(card.defId);
  if (d.xCost) return 0;
  const base = card.upgraded && d.upgradedCost !== undefined ? d.upgradedCost : d.cost;
  const delta = card.runeMods?.costDelta ?? 0;
  return Math.max(0, base - delta);
}

export function cardEffects(card: CardInst) {
  const d = getCard(card.defId);
  const base = card.upgraded ? d.upgradedEffects : d.effects;
  const mods = card.runeMods;
  if (!mods) return base;
  const bumped = base.map((e) => {
    if ((e.t === "damage" || e.t === "damageAll") && mods.damage) return { ...e, n: e.n + mods.damage };
    if ((e.t === "block" || e.t === "blockPerEnemy") && mods.block) return { ...e, n: e.n + mods.block };
    return e;
  });
  const extra = [...mods.extra];
  if (mods.damage && !base.some((e) => e.t === "damage" || e.t === "damageAll" || e.t === "damageX")) {
    extra.unshift({ t: "damage", n: mods.damage });
  }
  if (mods.block && !base.some((e) => e.t === "block" || e.t === "blockPerEnemy")) {
    extra.unshift({ t: "block", n: mods.block });
  }
  return extra.length ? [...bumped, ...extra] : bumped;
}

export function scaleN(n: number, card?: CardInst) {
  if (!card?.forge || card.forge === 1) return n;
  return Math.max(1, Math.floor(n * card.forge));
}

export function rewardPool(owner: CharacterId): CardDef[] {
  return Object.values(CARDS).filter(
    (c) =>
      c.rarity !== "starter" &&
      c.rarity !== "status" &&
      !c.grimoire &&
      !c.shop &&
      (c.owner === "shared" || c.owner === owner),
  );
}
