import type { EnemyDef } from "./types";
import { asset } from "@/lib/asset";

function still(id: string): Pick<EnemyDef, "art" | "poster"> {
  const src = asset(`art/pixel/${id}.png`);
  return { art: src, poster: src };
}

export const ENEMIES: Record<string, EnemyDef> = {
  acolyte: {
    id: "acolyte",
    name: "侍祭",
    ...still("acolyte"),
    biome: "shrine",
    maxHp: 32,
    pattern: [
      { kind: "attack", damage: 7 },
      { kind: "attack", damage: 11 },
      { kind: "defend", block: 8 },
    ],
  },
  fanatic: {
    id: "fanatic",
    name: "狂信者",
    ...still("fanatic"),
    biome: "shrine",
    maxHp: 42,
    tier: "elite",
    pattern: [
      { kind: "attack", damage: 9 },
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 12 },
    ],
  },
  drowned: {
    id: "drowned",
    name: "溺れた眷属",
    ...still("drowned"),
    biome: "reef",
    maxHp: 44,
    pattern: [
      { kind: "attack", damage: 9 },
      { kind: "defend", block: 10 },
      { kind: "attack", damage: 6, hits: 2 },
    ],
  },
  byakhee: {
    id: "byakhee",
    name: "翼ある飢え",
    ...still("byakhee"),
    biome: "void",
    maxHp: 38,
    tier: "elite",
    pattern: [
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 13 },
      { kind: "attack", damage: 8 },
    ],
  },
  coral: {
    id: "coral",
    name: "礁の衛士",
    ...still("coral"),
    biome: "reef",
    maxHp: 48,
    tier: "elite",
    pattern: [
      { kind: "defend", block: 10 },
      { kind: "attack", damage: 10 },
      { kind: "attack", damage: 6, hits: 2 },
    ],
  },
  starveling: {
    id: "starveling",
    name: "飢えし仔",
    ...still("starveling"),
    biome: "reef",
    maxHp: 86,
    tier: "elite",
    pattern: [
      { kind: "buff", strength: 2 },
      { kind: "attack", damage: 16 },
      { kind: "attack", damage: 8, hits: 2 },
      { kind: "defend", block: 14 },
    ],
  },
  serpent: {
    id: "serpent",
    name: "ムーの蛇人",
    ...still("serpent"),
    biome: "mu",
    maxHp: 54,
    pattern: [
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 12 },
      { kind: "defend", block: 9 },
      { kind: "attack", damage: 7, hits: 2 },
    ],
  },
  spawn: {
    id: "spawn",
    name: "ガタノトアの落とし子",
    ...still("spawn"),
    biome: "mu",
    maxHp: 62,
    pattern: [
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 11 },
      { kind: "buff", strength: 2 },
      { kind: "attack", damage: 15 },
    ],
  },
  migo: {
    id: "migo",
    name: "ミーゴ",
    ...still("migo"),
    biome: "void",
    maxHp: 40,
    pattern: [
      { kind: "attack", damage: 8 },
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 5, hits: 2 },
    ],
  },
  colour: {
    id: "colour",
    name: "星から来た色",
    ...still("colour"),
    biome: "colour",
    maxHp: 48,
    pattern: [
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 10 },
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 13 },
    ],
  },
  starvamp: {
    id: "starvamp",
    name: "星の吸血獣",
    ...still("starvamp"),
    biome: "void",
    maxHp: 56,
    tier: "elite",
    pattern: [
      { kind: "attack", damage: 14 },
      { kind: "attack", damage: 7, hits: 2 },
      { kind: "defend", block: 8 },
    ],
  },
  shan: {
    id: "shan",
    name: "シャガイの昆虫",
    ...still("shan"),
    biome: "void",
    maxHp: 36,
    pattern: [
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 9 },
      { kind: "attack", damage: 6, hits: 2 },
    ],
  },
  priest: {
    id: "priest",
    name: "尖塔の大司祭",
    ...still("priest"),
    biome: "shrine",
    maxHp: 168,
    signatureCardId: "revelation",
    cardsPerTurn: 2,
    deck: ["revelation", "lash", "bash", "ward", "chant"],
    pattern: [
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 18 },
      { kind: "attack", damage: 9, hits: 2 },
      { kind: "buff", strength: 3 },
      { kind: "attack", damage: 22 },
    ],
  },
  choir: {
    id: "choir",
    name: "塩の唱者",
    ...still("choir"),
    biome: "street",
    maxHp: 42,
    trait: "choir",
    signatureCardId: "chorusunity",
    cardsPerTurn: 2,
    deck: ["chorusunity", "strike", "sigil", "rite"],
    pattern: [
      { kind: "attack", damage: 8 },
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 6, hits: 2 },
      { kind: "defend", block: 8 },
    ],
  },
  nurse: {
    id: "nurse",
    name: "深きものの乳母",
    ...still("nurse"),
    biome: "reef",
    maxHp: 112,
    trait: "nurse",
    signatureCardId: "embrace",
    cardsPerTurn: 2,
    deck: ["embrace", "dressing", "bash", "all-vacuum"],
    pattern: [
      { kind: "defend", block: 16 },
      { kind: "attack", damage: 12 },
      { kind: "defend", block: 20 },
      { kind: "attack", damage: 9, hits: 2 },
      { kind: "buff", strength: 2 },
    ],
  },
  flock: {
    id: "flock",
    name: "飢えた翼",
    ...still("flock"),
    biome: "reef",
    maxHp: 52,
    signatureCardId: "flockrush",
    cardsPerTurn: 2,
    deck: ["flockrush", "lash", "all-glass", "ward"],
    pattern: [
      { kind: "attack", damage: 5, hits: 3 },
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 11 },
      { kind: "attack", damage: 4, hits: 3 },
    ],
  },
  warden: {
    id: "warden",
    name: "曲がる幾何の番",
    ...still("warden"),
    biome: "fold",
    maxHp: 108,
    trait: "liar",
    signatureCardId: "noneuclid",
    cardsPerTurn: 2,
    deck: ["noneuclid", "eldersign", "all-phase", "bash", "all-geo"],
    pattern: [
      { kind: "attack", damage: 16 },
      { kind: "defend", block: 14 },
      { kind: "debuff", weak: 2 },
      { kind: "attack", damage: 8, hits: 2 },
      { kind: "buff", strength: 2 },
    ],
  },
  bell: {
    id: "bell",
    name: "溺れた街の鐘",
    ...still("bell"),
    biome: "street",
    maxHp: 118,
    trait: "bell",
    signatureCardId: "tollbell",
    cardsPerTurn: 2,
    deck: ["tollbell", "all-necrosis", "all-zero", "ironwill"],
    pattern: [
      { kind: "attack", damage: 15 },
      { kind: "debuff", dread: 1 },
      { kind: "attack", damage: 7, hits: 2 },
      { kind: "buff", strength: 2 },
      { kind: "attack", damage: 20 },
    ],
  },
  nyar: {
    id: "nyar",
    name: "門番ナイアルラト",
    ...still("nyar"),
    biome: "throne",
    maxHp: 124,
    trait: "seal",
    signatureCardId: "pricewisdom",
    cardsPerTurn: 2,
    deck: ["pricewisdom", "all-necrosis", "rite", "all-vacuum", "eldersign"],
    pattern: [
      { kind: "debuff", seal: "attack", weak: 1 },
      { kind: "attack", damage: 16 },
      { kind: "debuff", seal: "skill" },
      { kind: "attack", damage: 9, hits: 2 },
      { kind: "buff", strength: 3 },
    ],
  },
  iha: {
    id: "iha",
    name: "緑の腐肉、イハ",
    ...still("iha"),
    biome: "throne",
    maxHp: 96,
    trait: "split",
    signatureCardId: "protosurge",
    cardsPerTurn: 2,
    deck: ["protosurge", "all-geo", "all-glass", "ironwill", "all-zero"],
    pattern: [
      { kind: "attack", damage: 14 },
      { kind: "defend", block: 10 },
      { kind: "attack", damage: 8, hits: 2 },
      { kind: "debuff", dread: 1 },
      { kind: "buff", strength: 2 },
    ],
  },
  herald: {
    id: "herald",
    name: "呼び声の使徒",
    ...still("herald"),
    biome: "throne",
    maxHp: 214,
    signatureCardId: "heraldscall",
    cardsPerTurn: 2,
    deck: ["heraldscall", "thecall", "all-zero", "ironwill", "eldersign"],
    pattern: [
      { kind: "debuff", dread: 1, weak: 2 },
      { kind: "attack", damage: 16, hits: 2 },
      { kind: "buff", strength: 3 },
      { kind: "attack", damage: 24 },
      { kind: "defend", block: 18 },
    ],
  },
  mouth: {
    id: "mouth",
    name: "口そのもの",
    ...still("mouth"),
    biome: "throne",
    maxHp: 268,
    signatureCardId: "devourmaw",
    cardsPerTurn: 2,
    deck: ["devourmaw", "thecall", "all-zero", "all-necrosis", "ironwill", "eldersign"],
    pattern: [
      { kind: "debuff", dread: 2 },
      { kind: "attack", damage: 12, hits: 3 },
      { kind: "buff", strength: 4 },
      { kind: "attack", damage: 28 },
      { kind: "attack", damage: 18, hits: 2 },
    ],
  },
};

export function getEnemy(id: string): EnemyDef {
  const e = ENEMIES[id];
  if (!e) throw new Error(`Unknown enemy ${id}`);
  return e;
}
